/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STR_H_RPCGEN
#define _STR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct strings {
	char *str1;
	char *str2;
};
typedef struct strings strings;

#define ADD_PROG 0x23451111
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  bool_t * add_1(strings *, CLIENT *);
extern  bool_t * add_1_svc(strings *, struct svc_req *);
#define count 2
extern  int * count_1(strings *, CLIENT *);
extern  int * count_1_svc(strings *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  bool_t * add_1();
extern  bool_t * add_1_svc();
#define count 2
extern  int * count_1();
extern  int * count_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_strings (XDR *, strings*);

#else /* K&R C */
extern bool_t xdr_strings ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STR_H_RPCGEN */
