/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "str.h"

bool_t *add_1_svc(strings *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	    if (strcmp(argp->str1, argp->str2) == 0) {
		result = TRUE; 
	    } else {
		result = FALSE; 
	    }

	return &result;
}

int *count_1_svc(strings *argp, struct svc_req *rqstp)
{
	static int  result;

	result = strlen(argp->str1) + strlen(argp->str2);

	return &result;
}
